import './globals.css'
import AppNav from '@/components/AppNav'
import { Footer } from '@/components/Footer';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className='min-h-screen flex flex-col justify-between'>
          <div>
            <AppNav />
            {children}
          </div>

          <Footer />
        </div>

      </body>
    </html>
  )
}
